spring:
  application:
    name: inventory-management

  datasource:
    url: jdbc:sqlite:inventory.db
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: false

  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

# Configuración de logging simplificada - Solo para desarrollo
logging:
  level:
    root: INFO
    com.meli.inventorymanagement: DEBUG
    com.meli.inventorymanagement.application.service: DEBUG
    com.meli.inventorymanagement.infrastructure.security: INFO
    com.meli.inventorymanagement.infrastructure.exception: DEBUG
    com.meli.inventorymanagement.infrastructure.adapter.input.rest: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.springframework.web: INFO
    org.springframework.boot: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/inventory-management.log
  logback:
    rollingpolicy:
      file-name-pattern: logs/inventory-management.%d{yyyy-MM-dd}.%i.log.gz
      max-file-size: 50MB
      max-history: 30
      total-size-cap: 1GB

jwt:
  secret: mySecretKeyForInventoryManagementSystemThatIsLongEnoughForHS256Algorithm
  expiration: 86400000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

# Configuración de actuator para desarrollo
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
  endpoint:
    health:
      show-details: always